### ISSUE TITLE
CZI: Invalid C index

### ISSUE THREAD

**Issue by dominikl** [ome/bioformats#4001] opened 2023-05-05 10:06 UTC
See [QA 32935](https://www.openmicroscopy.org/qa2/qa/feedback/32935/)

```
java.lang.IllegalArgumentException: Invalid C index: 1/1
	at loci.formats.FormatTools.getIndex(FormatTools.java:481)
	at loci.formats.FormatTools.getIndex(FormatTools.java:408)
	at loci.formats.FormatReader.getIndex(FormatReader.java:1076)
	at loci.formats.in.ZeissCZIReader.assignPlaneIndices(ZeissCZIReader.java:1981)
...
```

Can also be replicated with current Bioformats release `showinf` .

**Comment by melissalinkert** [comment] 2023-05-05 14:33
QA 32935 and 32932 are the same file (`md5sum` matches). Closing as duplicate of #3996.

**Closed as completed by melissalinkert** 2023-05-05 14:33 UTC
