### ISSUE TITLE
Opening CZI compressed with ZSTD does not allow access to series (pyramid levels)

### ISSUE THREAD

**Issue by sebi06** [ome/bioformats#4110] opened 2023-10-20 10:28 UTC
Dear BF Team,

- i created two CZI image datasets
- one is uncompressed the other one compressed via ZSTD (which will become the new default compression for ZEN)
- when I open the uncompressed CZI using the latest BF I get what I expect (5 pyramid levels)
- when I open the compressed CZI it opens directly while not offering the series selection (only the highest level is read)

<img width="426" alt="image" src="https://github.com/ome/bioformats/assets/3833249/56efe445-daef-44ca-8076-e35b61cc30a4">
<img width="983" alt="image" src="https://github.com/ome/bioformats/assets/3833249/4cbb4441-4fa2-4ba5-862c-02d4e0a7fe8f">

CZI Data:

https://www.dropbox.com/scl/fi/wauh69abwh9qdmj7l7bo6/TR_M-29_uncompressd.czi?rlkey=hbdh7k906ogdcavbccqysx56l&dl=0

https://www.dropbox.com/scl/fi/igjapws4kn5x0mvkpktbb/TR_M-29_ZSTD.czi?rlkey=2cdp4gzkv614huwpndiixqsb6&dl=0

**Comment by dgault** [comment] 2023-10-23 13:44
Thanks @sebi06 for opening the issue, I can confirm that I can reproduce the issue with Bio-Formats 7.0.1, the same issue can be seen in all versions since ZSTD compression was implemented. The provided sample files have been copied to `inbox/imagesc-83733`

**Comment by dgault** [comment] 2024-02-08 10:43
Closing as resolved by https://github.com/ome/bioformats/pull/4138

**Closed as completed** 2024-02-08 10:43 UTC
Labels: reader:ZeissCZI
