### ISSUE TITLE
[WARN] No pixel block error

### ISSUE THREAD

**Issue by naomicxia** [ome/bioformats#3242] opened 2018-10-04 19:23 UTC
Hello,
I am trying to read .oir files acquired from Olympus 2-P microscope. The files are quite large (2 channels, 15000 timepoints each). When I try to open them with Bio-formats I receive the following error:

Reading pixel blocks from /Volumes//5-18-18/5-18-18_3001873_m219_wmdelay0to0'5s-1.oir
[WARN] Unknown Immersion value 'SCALEVIEW-A' will be stored as "Other"
Reading pixel blocks from /Volumes//5-18-18/5-18-18_3001873_m219_wmdelay0to0'5s-1_00001
Reading pixel blocks from /Volumes/5-18-18/5-18-18_3001873_m219_wmdelay0to0'5s-1_00002
Reading pixel blocks from /Volumes/5-18-18/5-18-18_3001873_m219_wmdelay0to0'5s-1_00003
Reading pixel blocks from /Volumes/5-18-18/5-18-18_3001873_m219_wmdelay0to0'5s-1_00004
Reading pixel blocks from /Volumes//5-18-18/5-18-18_3001873_m219_wmdelay0to0'5s-1_00005
Reading pixel blocks from /Volumes/5-18-18/5-18-18_3001873_m219_wmdelay0to0'5s-1_00006
[WARN] No pixel blocks for plane #2202
[WARN] No pixel blocks for plane #2202
[WARN] No pixel blocks for plane #2330
[WARN] No pixel blocks for plane #2330
[WARN] No pixel blocks for plane #3008

And so on and so forth. It essentially processes the entire 30,000 images but after about 1000 frames there are no more pixels. I tried using the Bioformats command line tool (bfconvert) as well as the Matlab toolbox and replicated the same issue, so I am abit stumped here. Any help would be appreciated!

**Comment by dgault** [comment] 2018-10-08 10:01
Hi @naomicxia, thanks for opening the issue. This appears to be a new issue which we have not seen reported before, do you see the issue consistently with all your OIR files or is it only this particular fileset which is problematic? Also is it a single OIR file or is it a split multifile dataset?

If you can reproduce the issue with a smaller image then you can upload to https://www.openmicroscopy.org/qa2/qa/upload/ for us to test.

**Comment by sbesson** [comment] 2018-10-08 19:21
@naomicxia: thanks for the details. The original implementation of the Olympus OIR reader from [Bio-Formats 5.5.0](http://docs.openmicroscopy.org/bio-formats/5.5.0/about/whats-new.html) lacked support for multi-file datasets due to the absence of representative samples. However, support was added back in [Bio-Formats 5.8.0](http://docs.openmicroscopy.org/bio-formats/5.8.0/about/whats-new.html).

Which version of Bio-Formats have you tested? It might be your data is a variation of these multi-part OIR filesets we have not been seen before which is why getting representative datasets is crucial.

**Comment by naomicxia** [comment] 2018-10-08 20:14
I tested the newest version (5.9.2) about a week ago and replicated this No pixel blocks error in both the matlab and command land bio-formats packages . If there is a way I can upload my dataset to help with testing I would be happy to!

**Comment by sbesson** [comment] 2018-10-08 20:33
How big is your dataset? Below 2GB, you should be able to upload to the link send by @dgault in https://github.com/openmicroscopy/bioformats/issues/3242#issuecomment-427779872. For sample data larger than 2GB, we can give you private credentials for uploading it via FTP if you give us an email address.

**Comment by naomicxia** [comment] 2018-10-08 21:19
Unfortunately, it's slightly over 2GB.

**Comment by melissalinkert** [comment] 2018-10-09 17:54
@naomicxia : we can send you FTP credentials to upload the dataset, but we will need an email address to do so.  Probably the easiest thing to do is to go to https://www.openmicroscopy.org/qa2/qa/upload/ and upload a text file containing only your email address.  This will only be visible to the OME team, so your address will not be made public.  Once we have that, I will send you a private email with instructions for sending files via FTP.

**Comment by naomicxia** [comment] 2018-10-30 19:33
Hello, I just uploaded the txt file!

**Comment by melissalinkert** [comment] 2018-10-30 19:41
Thank you!  I have just sent you a private email with FTP credentials (subject: ```Sending large files to the OME team```).

**Comment by dgault** [comment] 2019-04-12 14:42
The same issue ([WARN] No pixel blocks for plane #999 and above) has also been reported in https://forum.image.sc/t/problems-opening-olympus-oir-files-using-bio-formats/24747. A sample file has also been provided in that thread which I have tested and reproduced the issue using 6.0.1.

The file in the latest thread is not a multipart file.

**Comment by dgault** [comment] 2019-04-15 14:10
A proposed fix for this has been opened in https://github.com/openmicroscopy/bioformats/pull/3349

**Comment by melissalinkert** [comment] 2023-08-09 17:05
Closing since #3349 was included in 6.1.0

**Closed by melissalinkert** 2023-08-09 17:05 UTC
